services:
  producer:
    build:
      context: ./producer
    container_name: producer-container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - shared-net

  consumer-email:
    build:
      context: ./consumer-email
    container_name: consumer-email-container
    restart: always
    ports:
      - "8081:8081"
    networks:
      - shared-net

  consumer-log:
    build:
      context: ./consumer-log
    container_name: consumer-log-container
    restart: always
    ports:
      - "8082:8082"
    networks:
      - shared-net

  consumer-stock:
    build:
      context: ./consumer-stock
    container_name: consumer-stock-container
    restart: always
    ports:
      - "8083:8083"
    networks:
      - shared-net

networks:
  shared-net:
    external: true