services:
  producer:
    build:
      context: ./producer
    container_name: producer-container
    restart: always
    ports:
      - "8080:8080"
    networks:
      - shared-net

  consumer-email:
    build:
      context: ./consumer-email
    container_name: consumer-email-container
    restart: always
    ports:
      - "8081:8081"
    networks:
      - shared-net

networks:
  shared-net:
    external: true