server:
  port: 8082

spring:
  application:
    name: consumer-log
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notiflow.log
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus